run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - exhaustive
    - forcetypeassert
    - gci
    - godot
    - gofmt
    - goimports
    - gocritic
    - goerr113
    - gosec
    - lll
    - misspell
    - nakedret
    - nilerr
    - noctx
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 15
  lll:
    line-length: 120
  gci:
    sections:
      - standard
      - prefix(busca-cnpj-2026)
      - default
  gocritic:
    enabled-tags: [diagnostic, performance, style]
  misspell:
    ignore-words:
      - federativo

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
