// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_panel.sql

package saasdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAPIClients = `-- name: CountAPIClients :one
SELECT COUNT(*)::bigint AS count FROM api_clients
`

func (q *Queries) CountAPIClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAPIClients = `-- name: ListAPIClients :many
SELECT id, name, email, status, monthly_quota, rate_limit_per_min, created_at
FROM api_clients
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAPIClientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAPIClients(ctx context.Context, arg ListAPIClientsParams) ([]ApiClient, error) {
	rows, err := q.db.Query(ctx, listAPIClients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiClient{}
	for rows.Next() {
		var i ApiClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.MonthlyQuota,
			&i.RateLimitPerMin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByClient = `-- name: ListAPIKeysByClient :many
SELECT id, client_id, key_prefix, label, expires_at, revoked_at, created_at
FROM api_keys
WHERE client_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByClientRow struct {
	ID        pgtype.UUID        `json:"id"`
	ClientID  pgtype.UUID        `json:"client_id"`
	KeyPrefix string             `json:"key_prefix"`
	Label     string             `json:"label"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAPIKeysByClient(ctx context.Context, clientID pgtype.UUID) ([]ListAPIKeysByClientRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByClientRow{}
	for rows.Next() {
		var i ListAPIKeysByClientRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.KeyPrefix,
			&i.Label,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentUsage = `-- name: ListRecentUsage :many
SELECT u.client_id, c.name AS client_name, u.date, u.request_count, u.cnpj_lookup_count
FROM api_usage_daily u
JOIN api_clients c ON c.id = u.client_id
ORDER BY u.date DESC, u.request_count DESC
LIMIT $1
`

type ListRecentUsageRow struct {
	ClientID        pgtype.UUID `json:"client_id"`
	ClientName      string      `json:"client_name"`
	Date            pgtype.Date `json:"date"`
	RequestCount    int64       `json:"request_count"`
	CnpjLookupCount int64       `json:"cnpj_lookup_count"`
}

func (q *Queries) ListRecentUsage(ctx context.Context, limit int32) ([]ListRecentUsageRow, error) {
	rows, err := q.db.Query(ctx, listRecentUsage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentUsageRow{}
	for rows.Next() {
		var i ListRecentUsageRow
		if err := rows.Scan(
			&i.ClientID,
			&i.ClientName,
			&i.Date,
			&i.RequestCount,
			&i.CnpjLookupCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageByClient = `-- name: ListUsageByClient :many
SELECT client_id, date, request_count, cnpj_lookup_count
FROM api_usage_daily
WHERE client_id = $1
ORDER BY date DESC
LIMIT $2
`

type ListUsageByClientParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListUsageByClient(ctx context.Context, arg ListUsageByClientParams) ([]ApiUsageDaily, error) {
	rows, err := q.db.Query(ctx, listUsageByClient, arg.ClientID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiUsageDaily{}
	for rows.Next() {
		var i ApiUsageDaily
		if err := rows.Scan(
			&i.ClientID,
			&i.Date,
			&i.RequestCount,
			&i.CnpjLookupCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND client_id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID       pgtype.UUID `json:"id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumUsageRequestsToday = `-- name: SumUsageRequestsToday :one
SELECT COALESCE(SUM(request_count), 0)::bigint AS total
FROM api_usage_daily
WHERE date = CURRENT_DATE
`

func (q *Queries) SumUsageRequestsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumUsageRequestsToday)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateClientStatus = `-- name: UpdateClientStatus :exec
UPDATE api_clients
SET status = $2
WHERE id = $1
`

type UpdateClientStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateClientStatus(ctx context.Context, arg UpdateClientStatusParams) error {
	_, err := q.db.Exec(ctx, updateClientStatus, arg.ID, arg.Status)
	return err
}
