// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_auth.sql

package saasdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminMFASecret = `-- name: GetAdminMFASecret :one
SELECT admin_id, secret_encrypted, created_at
FROM admin_mfa_secrets
WHERE admin_id = $1
`

func (q *Queries) GetAdminMFASecret(ctx context.Context, adminID pgtype.UUID) (AdminMfaSecret, error) {
	row := q.db.QueryRow(ctx, getAdminMFASecret, adminID)
	var i AdminMfaSecret
	err := row.Scan(&i.AdminID, &i.SecretEncrypted, &i.CreatedAt)
	return i, err
}

const getAdminUserByEmail = `-- name: GetAdminUserByEmail :one
SELECT id, email, password_hash, mfa_enabled, created_at, updated_at
FROM admin_users
WHERE email = $1
`

func (q *Queries) GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidRefreshToken = `-- name: GetValidRefreshToken :one
SELECT id, admin_id, token_hash, expires_at, revoked_at, created_at
FROM admin_refresh_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetValidRefreshToken(ctx context.Context, tokenHash []byte) (AdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, getValidRefreshToken, tokenHash)
	var i AdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAdminRefreshToken = `-- name: InsertAdminRefreshToken :one
INSERT INTO admin_refresh_tokens (admin_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, admin_id, token_hash, expires_at, revoked_at, created_at
`

type InsertAdminRefreshTokenParams struct {
	AdminID   pgtype.UUID        `json:"admin_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertAdminRefreshToken(ctx context.Context, arg InsertAdminRefreshTokenParams) (AdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, insertAdminRefreshToken, arg.AdminID, arg.TokenHash, arg.ExpiresAt)
	var i AdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE admin_refresh_tokens
SET revoked_at = now()
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const setAdminMFAEnabled = `-- name: SetAdminMFAEnabled :exec
UPDATE admin_users
SET mfa_enabled = $2, updated_at = now()
WHERE id = $1
`

type SetAdminMFAEnabledParams struct {
	ID         pgtype.UUID `json:"id"`
	MfaEnabled bool        `json:"mfa_enabled"`
}

func (q *Queries) SetAdminMFAEnabled(ctx context.Context, arg SetAdminMFAEnabledParams) error {
	_, err := q.db.Exec(ctx, setAdminMFAEnabled, arg.ID, arg.MfaEnabled)
	return err
}

const upsertAdminMFASecret = `-- name: UpsertAdminMFASecret :exec
INSERT INTO admin_mfa_secrets (admin_id, secret_encrypted)
VALUES ($1, $2)
ON CONFLICT (admin_id) DO UPDATE
SET secret_encrypted = EXCLUDED.secret_encrypted
`

type UpsertAdminMFASecretParams struct {
	AdminID         pgtype.UUID `json:"admin_id"`
	SecretEncrypted []byte      `json:"secret_encrypted"`
}

func (q *Queries) UpsertAdminMFASecret(ctx context.Context, arg UpsertAdminMFASecretParams) error {
	_, err := q.db.Exec(ctx, upsertAdminMFASecret, arg.AdminID, arg.SecretEncrypted)
	return err
}

const upsertAdminUser = `-- name: UpsertAdminUser :one
INSERT INTO admin_users (email, password_hash, mfa_enabled)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    mfa_enabled = EXCLUDED.mfa_enabled,
    updated_at = now()
RETURNING id, email, password_hash, mfa_enabled, created_at, updated_at
`

type UpsertAdminUserParams struct {
	Email        string `json:"email"`
	PasswordHash []byte `json:"password_hash"`
	MfaEnabled   bool   `json:"mfa_enabled"`
}

func (q *Queries) UpsertAdminUser(ctx context.Context, arg UpsertAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, upsertAdminUser, arg.Email, arg.PasswordHash, arg.MfaEnabled)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
