// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_keys.sql

package saasdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT k.id, k.client_id, k.key_prefix, k.revoked_at, k.expires_at,
       c.status, c.rate_limit_per_min, c.monthly_quota
FROM api_keys k
JOIN api_clients c ON c.id = k.client_id
WHERE k.key_hash = $1 AND k.revoked_at IS NULL
`

type GetAPIKeyByHashRow struct {
	ID              pgtype.UUID        `json:"id"`
	ClientID        pgtype.UUID        `json:"client_id"`
	KeyPrefix       string             `json:"key_prefix"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Status          string             `json:"status"`
	RateLimitPerMin int32              `json:"rate_limit_per_min"`
	MonthlyQuota    int32              `json:"monthly_quota"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash []byte) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.KeyPrefix,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RateLimitPerMin,
		&i.MonthlyQuota,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, name, email, status, monthly_quota, rate_limit_per_min, created_at
FROM api_clients
WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id pgtype.UUID) (ApiClient, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i ApiClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.MonthlyQuota,
		&i.RateLimitPerMin,
		&i.CreatedAt,
	)
	return i, err
}

const insertAPIClient = `-- name: InsertAPIClient :one
INSERT INTO api_clients (name, email, status, monthly_quota, rate_limit_per_min)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, status, monthly_quota, rate_limit_per_min, created_at
`

type InsertAPIClientParams struct {
	Name            string `json:"name"`
	Email           string `json:"email"`
	Status          string `json:"status"`
	MonthlyQuota    int32  `json:"monthly_quota"`
	RateLimitPerMin int32  `json:"rate_limit_per_min"`
}

func (q *Queries) InsertAPIClient(ctx context.Context, arg InsertAPIClientParams) (ApiClient, error) {
	row := q.db.QueryRow(ctx, insertAPIClient,
		arg.Name,
		arg.Email,
		arg.Status,
		arg.MonthlyQuota,
		arg.RateLimitPerMin,
	)
	var i ApiClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.MonthlyQuota,
		&i.RateLimitPerMin,
		&i.CreatedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (client_id, key_prefix, key_hash, label, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, client_id, key_prefix, label, expires_at, revoked_at, created_at
`

type InsertAPIKeyParams struct {
	ClientID  pgtype.UUID        `json:"client_id"`
	KeyPrefix string             `json:"key_prefix"`
	KeyHash   []byte             `json:"key_hash"`
	Label     string             `json:"label"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type InsertAPIKeyRow struct {
	ID        pgtype.UUID        `json:"id"`
	ClientID  pgtype.UUID        `json:"client_id"`
	KeyPrefix string             `json:"key_prefix"`
	Label     string             `json:"label"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (InsertAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.ClientID,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Label,
		arg.ExpiresAt,
	)
	var i InsertAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.KeyPrefix,
		&i.Label,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
