// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_usage.sql

package saasdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUsageDaily = `-- name: GetUsageDaily :one
SELECT client_id, date, request_count, cnpj_lookup_count
FROM api_usage_daily
WHERE client_id = $1 AND date = $2
`

type GetUsageDailyParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) GetUsageDaily(ctx context.Context, arg GetUsageDailyParams) (ApiUsageDaily, error) {
	row := q.db.QueryRow(ctx, getUsageDaily, arg.ClientID, arg.Date)
	var i ApiUsageDaily
	err := row.Scan(
		&i.ClientID,
		&i.Date,
		&i.RequestCount,
		&i.CnpjLookupCount,
	)
	return i, err
}

const upsertUsageDaily = `-- name: UpsertUsageDaily :exec
INSERT INTO api_usage_daily (client_id, date, request_count, cnpj_lookup_count)
VALUES ($1, $2, $3, $4)
ON CONFLICT (client_id, date) DO UPDATE SET
    request_count = api_usage_daily.request_count + EXCLUDED.request_count,
    cnpj_lookup_count = api_usage_daily.cnpj_lookup_count + EXCLUDED.cnpj_lookup_count
`

type UpsertUsageDailyParams struct {
	ClientID        pgtype.UUID `json:"client_id"`
	Date            pgtype.Date `json:"date"`
	RequestCount    int64       `json:"request_count"`
	CnpjLookupCount int64       `json:"cnpj_lookup_count"`
}

func (q *Queries) UpsertUsageDaily(ctx context.Context, arg UpsertUsageDailyParams) error {
	_, err := q.db.Exec(ctx, upsertUsageDaily,
		arg.ClientID,
		arg.Date,
		arg.RequestCount,
		arg.CnpjLookupCount,
	)
	return err
}
