// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package saasdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAdminAuditLog = `-- name: InsertAdminAuditLog :one
INSERT INTO admin_audit_log (admin_id, action, resource_type, resource_id, details)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, admin_id, action, resource_type, resource_id, details, created_at
`

type InsertAdminAuditLogParams struct {
	AdminID      pgtype.UUID `json:"admin_id"`
	Action       string      `json:"action"`
	ResourceType pgtype.Text `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	Details      []byte      `json:"details"`
}

func (q *Queries) InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, insertAdminAuditLog,
		arg.AdminID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Details,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}
