// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package saasdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditLog struct {
	ID           int64              `json:"id"`
	AdminID      pgtype.UUID        `json:"admin_id"`
	Action       string             `json:"action"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	Details      []byte             `json:"details"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AdminMfaSecret struct {
	AdminID         pgtype.UUID        `json:"admin_id"`
	SecretEncrypted []byte             `json:"secret_encrypted"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AdminRefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	AdminID   pgtype.UUID        `json:"admin_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AdminUser struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	MfaEnabled   bool               `json:"mfa_enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ApiClient struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	Status          string             `json:"status"`
	MonthlyQuota    int32              `json:"monthly_quota"`
	RateLimitPerMin int32              `json:"rate_limit_per_min"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID        pgtype.UUID        `json:"id"`
	ClientID  pgtype.UUID        `json:"client_id"`
	KeyPrefix string             `json:"key_prefix"`
	KeyHash   []byte             `json:"key_hash"`
	Label     string             `json:"label"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ApiUsageDaily struct {
	ClientID        pgtype.UUID `json:"client_id"`
	Date            pgtype.Date `json:"date"`
	RequestCount    int64       `json:"request_count"`
	CnpjLookupCount int64       `json:"cnpj_lookup_count"`
}
