// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package saasdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetAPIKeyByHash(ctx context.Context, keyHash []byte) (GetAPIKeyByHashRow, error)
	GetClientByID(ctx context.Context, id pgtype.UUID) (ApiClient, error)
	GetUsageDaily(ctx context.Context, arg GetUsageDailyParams) (ApiUsageDaily, error)
	InsertAPIClient(ctx context.Context, arg InsertAPIClientParams) (ApiClient, error)
	InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (InsertAPIKeyRow, error)
	UpsertUsageDaily(ctx context.Context, arg UpsertUsageDailyParams) error
}

var _ Querier = (*Queries)(nil)
