// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package saasdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAPIClients(ctx context.Context) (int64, error)
	GetAPIKeyByHash(ctx context.Context, keyHash []byte) (GetAPIKeyByHashRow, error)
	GetAdminMFASecret(ctx context.Context, adminID pgtype.UUID) (AdminMfaSecret, error)
	GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error)
	GetClientByID(ctx context.Context, id pgtype.UUID) (ApiClient, error)
	GetUsageDaily(ctx context.Context, arg GetUsageDailyParams) (ApiUsageDaily, error)
	GetValidRefreshToken(ctx context.Context, tokenHash []byte) (AdminRefreshToken, error)
	InsertAPIClient(ctx context.Context, arg InsertAPIClientParams) (ApiClient, error)
	InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (InsertAPIKeyRow, error)
	InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) (AdminAuditLog, error)
	InsertAdminRefreshToken(ctx context.Context, arg InsertAdminRefreshTokenParams) (AdminRefreshToken, error)
	ListAPIClients(ctx context.Context, arg ListAPIClientsParams) ([]ApiClient, error)
	ListAPIKeysByClient(ctx context.Context, clientID pgtype.UUID) ([]ListAPIKeysByClientRow, error)
	ListRecentUsage(ctx context.Context, limit int32) ([]ListRecentUsageRow, error)
	ListUsageByClient(ctx context.Context, arg ListUsageByClientParams) ([]ApiUsageDaily, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	SetAdminMFAEnabled(ctx context.Context, arg SetAdminMFAEnabledParams) error
	SumUsageRequestsToday(ctx context.Context) (int64, error)
	UpdateClientStatus(ctx context.Context, arg UpdateClientStatusParams) error
	UpsertAdminMFASecret(ctx context.Context, arg UpsertAdminMFASecretParams) error
	UpsertAdminUser(ctx context.Context, arg UpsertAdminUserParams) (AdminUser, error)
	UpsertUsageDaily(ctx context.Context, arg UpsertUsageDailyParams) error
}

var _ Querier = (*Queries)(nil)
