-- Drop reference tables
DROP TABLE IF EXISTS cnaes CASCADE;
DROP TABLE IF EXISTS qualificacoes CASCADE;
DROP TABLE IF EXISTS paises CASCADE;
DROP TABLE IF EXISTS naturezas CASCADE;
DROP TABLE IF EXISTS municipios CASCADE;
DROP TABLE IF EXISTS motivos CASCADE;
