// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: empresa.sql

package cnpjdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEmpresaByBasico = `-- name: GetEmpresaByBasico :one
SELECT
    emp.cnpj_basico,
    emp.razao_social,
    emp.natureza_juridica,
    COALESCE(n.descricao, '') AS natureza_descricao,
    emp.porte_empresa,
    emp.capital_social
FROM empresas emp
LEFT JOIN naturezas n ON emp.natureza_juridica = n.codigo
WHERE emp.cnpj_basico = $1
`

type GetEmpresaByBasicoRow struct {
	CnpjBasico        string         `json:"cnpj_basico"`
	RazaoSocial       string         `json:"razao_social"`
	NaturezaJuridica  pgtype.Text    `json:"natureza_juridica"`
	NaturezaDescricao string         `json:"natureza_descricao"`
	PorteEmpresa      pgtype.Text    `json:"porte_empresa"`
	CapitalSocial     pgtype.Numeric `json:"capital_social"`
}

func (q *Queries) GetEmpresaByBasico(ctx context.Context, cnpjBasico string) (GetEmpresaByBasicoRow, error) {
	row := q.db.QueryRow(ctx, getEmpresaByBasico, cnpjBasico)
	var i GetEmpresaByBasicoRow
	err := row.Scan(
		&i.CnpjBasico,
		&i.RazaoSocial,
		&i.NaturezaJuridica,
		&i.NaturezaDescricao,
		&i.PorteEmpresa,
		&i.CapitalSocial,
	)
	return i, err
}
