// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: estabelecimento.sql

package cnpjdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEstabelecimentoByCNPJ = `-- name: GetEstabelecimentoByCNPJ :one
SELECT
    e.cnpj_completo,
    e.cnpj_basico,
    e.nome_fantasia,
    e.situacao_cadastral,
    e.uf,
    COALESCE(m.descricao, '') AS municipio_nome,
    e.municipio AS municipio_codigo,
    e.cnae_fiscal_principal,
    COALESCE(c.descricao, '') AS cnae_descricao,
    e.tipo_logradouro,
    e.logradouro,
    e.numero,
    e.complemento,
    e.bairro,
    e.cep,
    e.ddd_1,
    e.telefone_1,
    e.ddd_2,
    e.telefone_2,
    e.email,
    COALESCE(emp.razao_social, '') AS razao_social
FROM estabelecimentos e
LEFT JOIN empresas emp ON e.cnpj_basico = emp.cnpj_basico
LEFT JOIN cnaes c ON e.cnae_fiscal_principal = c.codigo
LEFT JOIN municipios m ON e.municipio = m.codigo
WHERE e.cnpj_completo = $1
`

type GetEstabelecimentoByCNPJRow struct {
	CnpjCompleto        pgtype.Text `json:"cnpj_completo"`
	CnpjBasico          string      `json:"cnpj_basico"`
	NomeFantasia        pgtype.Text `json:"nome_fantasia"`
	SituacaoCadastral   pgtype.Text `json:"situacao_cadastral"`
	Uf                  pgtype.Text `json:"uf"`
	MunicipioNome       string      `json:"municipio_nome"`
	MunicipioCodigo     pgtype.Text `json:"municipio_codigo"`
	CnaeFiscalPrincipal pgtype.Text `json:"cnae_fiscal_principal"`
	CnaeDescricao       string      `json:"cnae_descricao"`
	TipoLogradouro      pgtype.Text `json:"tipo_logradouro"`
	Logradouro          pgtype.Text `json:"logradouro"`
	Numero              pgtype.Text `json:"numero"`
	Complemento         pgtype.Text `json:"complemento"`
	Bairro              pgtype.Text `json:"bairro"`
	Cep                 pgtype.Text `json:"cep"`
	Ddd1                pgtype.Text `json:"ddd_1"`
	Telefone1           pgtype.Text `json:"telefone_1"`
	Ddd2                pgtype.Text `json:"ddd_2"`
	Telefone2           pgtype.Text `json:"telefone_2"`
	Email               pgtype.Text `json:"email"`
	RazaoSocial         string      `json:"razao_social"`
}

func (q *Queries) GetEstabelecimentoByCNPJ(ctx context.Context, cnpjCompleto pgtype.Text) (GetEstabelecimentoByCNPJRow, error) {
	row := q.db.QueryRow(ctx, getEstabelecimentoByCNPJ, cnpjCompleto)
	var i GetEstabelecimentoByCNPJRow
	err := row.Scan(
		&i.CnpjCompleto,
		&i.CnpjBasico,
		&i.NomeFantasia,
		&i.SituacaoCadastral,
		&i.Uf,
		&i.MunicipioNome,
		&i.MunicipioCodigo,
		&i.CnaeFiscalPrincipal,
		&i.CnaeDescricao,
		&i.TipoLogradouro,
		&i.Logradouro,
		&i.Numero,
		&i.Complemento,
		&i.Bairro,
		&i.Cep,
		&i.Ddd1,
		&i.Telefone1,
		&i.Ddd2,
		&i.Telefone2,
		&i.Email,
		&i.RazaoSocial,
	)
	return i, err
}
