// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package cnpjdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cnae struct {
	Codigo    string `json:"codigo"`
	Descricao string `json:"descricao"`
}

type Empresa struct {
	UuidID                    pgtype.UUID      `json:"uuid_id"`
	CnpjBasico                string           `json:"cnpj_basico"`
	RazaoSocial               string           `json:"razao_social"`
	NaturezaJuridica          pgtype.Text      `json:"natureza_juridica"`
	QualificacaoResponsavel   pgtype.Text      `json:"qualificacao_responsavel"`
	CapitalSocial             pgtype.Numeric   `json:"capital_social"`
	PorteEmpresa              pgtype.Text      `json:"porte_empresa"`
	EnteFederativoResponsavel pgtype.Text      `json:"ente_federativo_responsavel"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
	UpdatedAt                 pgtype.Timestamp `json:"updated_at"`
}

type Estabelecimento struct {
	ID                        pgtype.Int8      `json:"id"`
	UuidID                    pgtype.UUID      `json:"uuid_id"`
	CnpjBasico                string           `json:"cnpj_basico"`
	CnpjOrdem                 string           `json:"cnpj_ordem"`
	CnpjDv                    string           `json:"cnpj_dv"`
	CnpjCompleto              pgtype.Text      `json:"cnpj_completo"`
	IdentificadorMatrizFilial pgtype.Text      `json:"identificador_matriz_filial"`
	NomeFantasia              pgtype.Text      `json:"nome_fantasia"`
	SituacaoCadastral         pgtype.Text      `json:"situacao_cadastral"`
	DataSituacaoCadastral     pgtype.Date      `json:"data_situacao_cadastral"`
	MotivoSituacaoCadastral   pgtype.Text      `json:"motivo_situacao_cadastral"`
	NomeCidadeExterior        pgtype.Text      `json:"nome_cidade_exterior"`
	Pais                      pgtype.Text      `json:"pais"`
	DataInicioAtividade       pgtype.Date      `json:"data_inicio_atividade"`
	CnaeFiscalPrincipal       pgtype.Text      `json:"cnae_fiscal_principal"`
	CnaeFiscalSecundaria      pgtype.Text      `json:"cnae_fiscal_secundaria"`
	TipoLogradouro            pgtype.Text      `json:"tipo_logradouro"`
	Logradouro                pgtype.Text      `json:"logradouro"`
	Numero                    pgtype.Text      `json:"numero"`
	Complemento               pgtype.Text      `json:"complemento"`
	Bairro                    pgtype.Text      `json:"bairro"`
	Cep                       pgtype.Text      `json:"cep"`
	Uf                        pgtype.Text      `json:"uf"`
	Municipio                 pgtype.Text      `json:"municipio"`
	Ddd1                      pgtype.Text      `json:"ddd_1"`
	Telefone1                 pgtype.Text      `json:"telefone_1"`
	Ddd2                      pgtype.Text      `json:"ddd_2"`
	Telefone2                 pgtype.Text      `json:"telefone_2"`
	DddFax                    pgtype.Text      `json:"ddd_fax"`
	Fax                       pgtype.Text      `json:"fax"`
	Email                     pgtype.Text      `json:"email"`
	SituacaoEspecial          pgtype.Text      `json:"situacao_especial"`
	DataSituacaoEspecial      pgtype.Date      `json:"data_situacao_especial"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
}

type Motivo struct {
	Codigo    string `json:"codigo"`
	Descricao string `json:"descricao"`
}

type Municipio struct {
	Codigo    string      `json:"codigo"`
	Descricao string      `json:"descricao"`
	Uf        pgtype.Text `json:"uf"`
}

type Natureza struct {
	Codigo    string `json:"codigo"`
	Descricao string `json:"descricao"`
}

type Paise struct {
	Codigo    string `json:"codigo"`
	Descricao string `json:"descricao"`
}

type Qualificaco struct {
	Codigo    string `json:"codigo"`
	Descricao string `json:"descricao"`
}

type Simple struct {
	UuidID              pgtype.UUID `json:"uuid_id"`
	CnpjBasico          string      `json:"cnpj_basico"`
	OpcaoSimples        pgtype.Text `json:"opcao_simples"`
	DataOpcaoSimples    pgtype.Date `json:"data_opcao_simples"`
	DataExclusaoSimples pgtype.Date `json:"data_exclusao_simples"`
	OpcaoMei            pgtype.Text `json:"opcao_mei"`
	DataOpcaoMei        pgtype.Date `json:"data_opcao_mei"`
	DataExclusaoMei     pgtype.Date `json:"data_exclusao_mei"`
}

type Socio struct {
	ID                        int64            `json:"id"`
	UuidID                    pgtype.UUID      `json:"uuid_id"`
	CnpjBasico                string           `json:"cnpj_basico"`
	IdentificadorSocio        pgtype.Text      `json:"identificador_socio"`
	NomeSocio                 string           `json:"nome_socio"`
	CpfCnpjSocio              pgtype.Text      `json:"cpf_cnpj_socio"`
	QualificacaoSocio         pgtype.Text      `json:"qualificacao_socio"`
	DataEntradaSociedade      pgtype.Date      `json:"data_entrada_sociedade"`
	Pais                      pgtype.Text      `json:"pais"`
	RepresentanteLegal        pgtype.Text      `json:"representante_legal"`
	NomeRepresentante         pgtype.Text      `json:"nome_representante"`
	QualificacaoRepresentante pgtype.Text      `json:"qualificacao_representante"`
	FaixaEtaria               pgtype.Text      `json:"faixa_etaria"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
}
