// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package cnpjdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetEmpresaByBasico(ctx context.Context, cnpjBasico string) (GetEmpresaByBasicoRow, error)
	GetEstabelecimentoByCNPJ(ctx context.Context, cnpjCompleto pgtype.Text) (GetEstabelecimentoByCNPJRow, error)
	GetSimplesByBasico(ctx context.Context, cnpjBasico string) (GetSimplesByBasicoRow, error)
	ListSociosByBasico(ctx context.Context, cnpjBasico string) ([]ListSociosByBasicoRow, error)
}

var _ Querier = (*Queries)(nil)
