// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: simples.sql

package cnpjdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSimplesByBasico = `-- name: GetSimplesByBasico :one
SELECT
    opcao_simples,
    data_opcao_simples,
    data_exclusao_simples,
    opcao_mei,
    data_opcao_mei,
    data_exclusao_mei
FROM simples
WHERE cnpj_basico = $1
`

type GetSimplesByBasicoRow struct {
	OpcaoSimples        pgtype.Text `json:"opcao_simples"`
	DataOpcaoSimples    pgtype.Date `json:"data_opcao_simples"`
	DataExclusaoSimples pgtype.Date `json:"data_exclusao_simples"`
	OpcaoMei            pgtype.Text `json:"opcao_mei"`
	DataOpcaoMei        pgtype.Date `json:"data_opcao_mei"`
	DataExclusaoMei     pgtype.Date `json:"data_exclusao_mei"`
}

func (q *Queries) GetSimplesByBasico(ctx context.Context, cnpjBasico string) (GetSimplesByBasicoRow, error) {
	row := q.db.QueryRow(ctx, getSimplesByBasico, cnpjBasico)
	var i GetSimplesByBasicoRow
	err := row.Scan(
		&i.OpcaoSimples,
		&i.DataOpcaoSimples,
		&i.DataExclusaoSimples,
		&i.OpcaoMei,
		&i.DataOpcaoMei,
		&i.DataExclusaoMei,
	)
	return i, err
}
