// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: socios.sql

package cnpjdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSociosByBasico = `-- name: ListSociosByBasico :many
SELECT
    s.nome_socio,
    s.qualificacao_socio,
    COALESCE(q.descricao, '') AS qualificacao_descricao,
    s.data_entrada_sociedade
FROM socios s
LEFT JOIN qualificacoes q ON s.qualificacao_socio = q.codigo
WHERE s.cnpj_basico = $1
ORDER BY s.nome_socio
`

type ListSociosByBasicoRow struct {
	NomeSocio             string      `json:"nome_socio"`
	QualificacaoSocio     pgtype.Text `json:"qualificacao_socio"`
	QualificacaoDescricao string      `json:"qualificacao_descricao"`
	DataEntradaSociedade  pgtype.Date `json:"data_entrada_sociedade"`
}

func (q *Queries) ListSociosByBasico(ctx context.Context, cnpjBasico string) ([]ListSociosByBasicoRow, error) {
	rows, err := q.db.Query(ctx, listSociosByBasico, cnpjBasico)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSociosByBasicoRow{}
	for rows.Next() {
		var i ListSociosByBasicoRow
		if err := rows.Scan(
			&i.NomeSocio,
			&i.QualificacaoSocio,
			&i.QualificacaoDescricao,
			&i.DataEntradaSociedade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
